x-common-nginx: &common-nginx
  ports:
    - 3000:80

services:
  nginx:
    <<: *common-nginx
    profiles:
      - prod
    volumes:
      - ./config.js:/var/www/config.js
    build: .

  vite:
    build:
      target: frontend
    volumes:
      - ./src:/app/src
      # - ./public:/app/public
      - ./config.js:/app/public/config.js
    ports:
      - "3000:3000"
    profiles:
      - dev
