x-common-nginx:
  &common-nginx
  ports:
    - 8000:80

services:
  nginx:
    <<: *common-nginx
    profiles:
      - prod
    image: ghcr.io/ninanor/nina-map-explorer:main
    build: .
    volumes:
      - ./datasets:/var/www/datasets:ro
  nginx-dev:
    <<: *common-nginx
    profiles:
      - dev
    image: nginx
    volumes:
      - ./datasets:/var/www/datasets:ro
      - ./nginx/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
  vite:
    build:
      target: frontend
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    profiles:
      - dev
