x-common-nginx:
  &common-nginx
  ports:
    - 8001:80

services:
  nginx:
    <<: *common-nginx
    profiles:
      - prod
    image: ghcr.io/ninanor/nina-map-explorer:main
    build: .

  vite:
    build:
      target: frontend
    volumes:
      - ./src:/app/src
      # - ./public:/app/public
      - ./config.js:/app/public/config.js
    ports:
      - "3000:3000"
    profiles:
      - dev
